MODEL:
  META_ARCHITECTURE: "TFCOS"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  BACKBONE:
    NAME: "build_retinanet_resnet_fpn_backbone"
    FREEZE_AT: -1
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  CHECKPOINT_PERIOD: 40000
  IMS_PER_BATCH: 16
  BASE_LR: 0.01  # Note that RetinaNet uses a different default learning rate
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  WARMUP_ITERS: 1500
INPUT:
  MIN_SIZE_TRAIN: (800, )
