_BASE_: "Base-SLRESNET-FCOS.yaml"
MODEL:
  SLRESNETS:
    NORM: "SyncBN"
    DEPTH: 50
    WIDTH_MULT: 0.25
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 1333
SOLVER:
  CHECKPOINT_PERIOD: 40000
  WARMUP_ITERS: 500
  # IMS_PER_BATCH: 8
  IMS_PER_BATCH: 16
  BASE_LR: 0.01  # Note that RetinaNet uses a different default learning rate
  # STEPS: (120000, 160000)
  # MAX_ITER: 180000
  STEPS: (60000, 80000)
  MAX_ITER: 90000