_BASE_: "Base-SLRESNET-FCOS.yaml"
MODEL:
  META_ARCHITECTURE: "SFCOS"
  WEIGHTS: "/data/qilu/projects/MODEL/FCOS-SLR50-025-T12_JOINT/model_final.pth"
  SLRESNETS:
    NORM: "SyncBN"
    DEPTH: 50
    WIDTH_MULT: 0.25
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 1333
SOLVER:
  CHECKPOINT_PERIOD: 40000
  WARMUP_ITERS: 500
  # IMS_PER_BATCH: 8
  IMS_PER_BATCH: 32
  BASE_LR: 0.02  # Note that RetinaNet uses a different default learning rate
  # STEPS: (120000, 160000)
  # MAX_ITER: 180000
  STEPS: (30000, 40000)
  MAX_ITER: 45000