_BASE_: "Base-SLRESNET-FCOS.yaml"
MODEL:
  SLRESNETS:
    DEPTH: 50
    WIDTH_MULT: 0.75
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 1333
SOLVER:
  CHECKPOINT_PERIOD: 80000
  WARMUP_ITERS: 500
  IMS_PER_BATCH: 8
  BASE_LR: 0.01  # Note that RetinaNet uses a different default learning rate
  STEPS: (120000, 160000)
  MAX_ITER: 180000